# file: C:\Users\10129\AppData\Roaming\Python\Python313\site-packages\pydantic\main.py
# hypothesis_version: 6.138.15

[', ', 'BaseModel', 'IncEx', 'ModelT', '_', '__annotations__', '__delete__', '__dict__', '__doc__', '__get__', '__module__', '__name__', '__orig_bases__', '__parameters__', '__pydantic_extra__', '__pydantic_fields__', '__pydantic_private__', '__root__', '__set__', 'allow', 'args', 'cached_property', 'create_model', 'error', 'extra', 'extra_known', 'from_attributes', 'frozen', 'frozen_field', 'frozen_instance', 'input', 'json', 'loc', 'model_config', 'model_field', 'model_post_init', 'none', 'origin', 'parameters', 'private', 'python', 'serializer', 'type', 'type[ModelT]', 'type_error', 'utf8', 'validate_assignment', 'validation', 'validator', 'value_error', 'warn']